name: fot-valuing-actions
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel=7.2.0
  - ipywidgets=8.1.8
  - numpy=2.3.5
  - pandas=3.0.0
  - scipy=1.17.0
  - scikit-learn=1.8.0
  - scikit-plot=0.3.7
  - tqdm=4.67.3
  - xgboost=3.1.3
  - matplotlib=3.10.8
  - pip=24.3
  - pip:
    - cloudpickle==3.1.2
    - matplotlib-inline==0.2.1
    - matplotsoccer==0.0.8
    - numba==0.63.1
    - shap==0.50.0
    - socceraction==0.2.0
    - "scikit-plot @ git+https://github.com/reiinakano/scikit-plot.git@2dd3e6a76df77edcd"
